TodayILearned/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from feed import urls as feed_urls
from profiles import urls as profile_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),
    path('profile/', include(profile_urls, namespace='profiles')),
    url('', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # this is not safe for production

feed/urls.py
from django.urls import path
from . import views

app_name = "feed"

urlpatterns = [
	path("", views.HomePage.as_view(), name="index"),
	path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
	path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name ="profiles"

urlpatterns = [
	path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
	path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
]

feed/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
	text = models.CharField(max_length=240)
	details = models.TextField(null=True)
	date = models.DateTimeField(auto_now=True)
	tag = models.CharField(max_length=32, null=True)
	author = models.ForeignKey(
		User,
		on_delete=models.CASCADE, # when user is deleted, delete posts
	)

	def __str__(self):
		return self.text[0:100]

followers/models.py
from django.db import models
from django.contrib.auth.models import User


class Follower(models.Model):
	followed_by = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		related_name='following',
	)
	following = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		related_name='followed_by',
	)

	def __str__(self):
		return f"{self.followed_by.id} is following {self.following.id}"

	class Meta:
		unique_together = ("followed_by", "following")

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

class Profile(models.Model):
	user = models.OneToOneField(
		User,
		on_delete=models.CASCADE,
		related_name="profile",
	)
	image = ImageField(upload_to="profiles")

	def __str__(self):
		return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	""" Create new profile object when Django user is created """
	if created:
		Profile.objects.create(user=instance)

feed/views.py
from followers.models import Follower
from django.http import request
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from followers.models import Follower
from .models import Post

class HomePage(TemplateView):
	http_method_names = ["get"]
	template_name = "feed/homepage.html"

	def dispatch(self, request, *args, **kwargs):
		self.request = request
		return super().dispatch(request, *args, **kwargs)

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		if self.request.user.is_authenticated:
			following = list(
				Follower.objects.filter(followed_by=self.request.user).values_list('following', flat=True)
			)
			if not following:
				context['posts'] = Post.objects.all().order_by('-id')[0:30]
			else:
				following.append(self.request.user)
				context['posts'] = Post.objects.filter(author__in=following).order_by('-id')[0:60]
		else:
			context['posts'] = Post.objects.all().order_by('-id')[0:30]

		return context

class PostDetailView(LoginRequiredMixin, DetailView):
	http_method_names = ["get"]
	template_name = "feed/detail.html"
	model = Post
	context_object_name = "post"

class CreateNewPost(LoginRequiredMixin, CreateView):
	model = Post
	template_name = "feed/create.html"
	fields = ['text', 'details', 'tag']
	success_url = "/"

	def post(self, request, *args, **kwargs):
		post = Post.objects.create(
			author=request.user,
			text=request.POST.get("text"),
			tag=request.POST.get("tag"),
			details=request.POST.get("details"),
		)
		return render(
			request,
			"includes/post.html",
			{
				"post": post,
			},
			content_type="application/html",
		)

	def dispatch(self, request, *args, **kwargs):
		self.request = request
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.author = self.request.user
		obj.save()
		return super().form_valid(form)

followers/views.py
from django.shortcuts import render

# Create your views here.

profiles/views.py
from django.contrib.auth.models import User
from django.http.response import HttpResponseBadRequest, JsonResponse
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from followers.models import Follower

from feed.models import Post

class ProfileDetailView(DetailView):
	http_method_names = ["get"]
	template_name = "profiles/detail.html"
	model = User
	context_object_name ="user"
	slug_field = "username"
	slug_url_kwarg = "username"

	def dispatch(self, request, *args, **kwargs):
		self.request = request
		return super().dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		user = self.get_object()
		context = super().get_context_data(**kwargs)
		context['total_posts'] = Post.objects.filter(author=user).count
		context['followers'] = Follower.objects.filter(following=user).count
		context['followed_by'] = Follower.objects.filter(followed_by=user).count

		print(context['followers'])

		if self.request.user.is_authenticated:
			context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user)

		return context

class FollowView(LoginRequiredMixin,View):
	http_method_names = ["post"]

	def post(self, request, *args, **kwargs):
		data = request.POST.dict()
		if "action" not in data or "username" not in data:
			return HttpResponseBadRequest({"Missing Data"})

		try:
			other_user = User.objects.get(username=data['username'])
		except User.DoesNotExist:
			return HttpResponseBadRequest("Missing User")

		if data['action'] == "follow":
			follower, created = Follower.objects.get_or_create(
				followed_by=request.user,
				following=other_user,
			)
		else:
			try:
				follower = Follower.objects.get(
					followed_by=request.user,
					following=other_user
				)
			except Follower.DoesNotExist:
				follower = None

			if follower:
				follower.delete()

		return JsonResponse({
			"success": True,
			"wording": "Unfollow" if data['action'] == "follow" else "Follow",
		})

TodayILearned/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block head_title %}Default{% endblock %}</title>
		<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
		<!-- navigation from https://tailwindcomponents.com/component/jed-dylan-lee -->
	</head>
	<body>
		{% load static %}
		<div class="min-h-screen flex flex-row flex-auto flex-shrink-0 antialiased bg-gray-50 text-gray-800">
			<div class="flex flex-col w-64 bg-gray-900 h-auto shadow-lg">
				{% include "navigation.html" %}
			</div>
			<div class="flex flex-col container mx-auto p-16">
				{% block body %}
					{% block content %}{% endblock %}
				{% endblock %}
			</div>
			<div class="flex flex-col w-64 bg-gray-900 h-auto shadow-lg"></div>
		</div>

		<!-- modal -->
		<div id="new-post-div" >
			{% csrf_token %}
			<div class="flex items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-75 hidden new-post-modal">
				<div class="editor mx-auto w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-2xl bg-white rounded">
					<input class="title bg-gray-100 border border-gray-300 p-2 outline-none" spellcheck="false" placeholder="Tag" type="text" id="tag" name="tag" maxlength="32" required="">
					<div class="count ml-auto text-gray-400 text-xs font-semibold mb-4"><span id="cur_tag">0</span>/32</div>
					<input class="title bg-gray-100 border border-gray-300 p-2 outline-none" spellcheck="false" placeholder="Summary" id="text" name="text" maxlength="240" required="" data-post-url="{% url 'feed:new_post' %}">
					<div class="count ml-auto text-gray-400 text-xs font-semibold mb-4"><span id="cur_text">0</span>/240</div>
					<textarea class="description bg-gray-100 sec p-3 h-60 border border-gray-300 outline-none mb-4" spellcheck="false" placeholder="Details" id="details" name="details"></textarea>
					<!-- icons -->
					<div class="icons flex text-gray-500 m-2">
						<svg class="mr-2 cursor-pointer hover:text-gray-700 border rounded-full p-1 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
						<svg class="mr-2 cursor-pointer hover:text-gray-700 border rounded-full p-1 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
						<svg class="mr-2 cursor-pointer hover:text-gray-700 border rounded-full p-1 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" /></svg>
					</div>
					<!-- buttons -->
					<div class="buttons flex">
						<button id="cancel-new-post" class="ml-auto bg-white text-gray-800 font-bold rounded border-b-2 border-red-500 hover:border-red-600 hover:bg-red-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center">
							<span class="mr-2">Cancel</span>
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
							<path fill="currentcolor" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z"/>
							</svg>
						</button>
						<button id="create-post" class=" mx-2 bg-white text-gray-800 font-bold rounded border-b-2 border-blue-500 hover:border-blue-600 hover:bg-blue-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit">
							<span class="mr-2">Create Post</span>
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
								<path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
							</svg>
						</button>
					</div>
				</div>
			</div>
		</div>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
		<script src="{% static 'js/main.js' %}"></script>
	</body>
</html>

TodayILearned/templates/includes/post.html
{% load thumbnail %}
{% load tz %}

<!-- https://tailwindcomponents.com/component/post-artical -->
<div class="max-w-4xl px-10 w-1/2 mx-auto my-4 py-6 bg-white rounded-lg shadow-md">
	<div class="flex justify-between items-center">

		<div class="mb-3">
			<a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
				{% if post.author.profile.image != "1" %}
					{% thumbnail post.author.profile.image "100x100" crop="center" as im %}
						<img class="rounded-full h-10 w-10 flex items-center justify-center mr-3 border-2 border-blue-500" src="{{ im.url }}" alt="avatar">
					{% endthumbnail %}
				{% else %}
					<img src="https://www.publicdomainpictures.net/pictures/40000/velka/question-mark.jpg" alt="" class="rounded-full h-10 w-10 flex items-center justify-center mr-3 border-2 border-blue-500">
				{% endif %}

				<h1 class="text-gray-700 font-bold">
					<!-- TODO: add settings to determine if users want to share their real names -->
					{% if post.author.first_name or post.author.last_name %}
						{{post.author.first_name}} {{post.author.last_name}}
					{% else %}
						{{post.author.username}}
					{% endif %}
				</h1>
			</a>
		</div>
		{% if post.tag %}
			<a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-blue-500" href="#">{{post.tag}}</a>
		{% endif %}
	</div>
	<div class="mt-2">
		<p class="mt-2 text-gray-600">{{post.text}}</p>
	</div>
	<div class="flex justify-between items-center mt-4">
		<a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">Read More</a>
		<span class="font-light text-gray-600">{{post.date|localtime}}</span>
	</div>
</div>

feed/templates/feed/create.html
{% extends "base.html" %}

{% block head_title%}Create New Post{% endblock head_title %}

{% block body %}

	<form method="POST" action=".">
		{% csrf_token %}
		<!-- https://tailwindcomponents.com/component/post-making-form -->
		<div class="heading text-center font-bold text-2xl m-5 text-gray-800">Create New Post</div>
		<div class="editor mx-auto w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-2xl">
			<input class="title bg-gray-100 border border-gray-300 p-2 outline-none" spellcheck="false" placeholder="Tag" type="text" id="tag" name="tag" maxlength="32" required="">
			<div class="count ml-auto text-gray-400 text-xs font-semibold mb-4"><span id="cur_tag">0</span>/32</div>
			<input class="title bg-gray-100 border border-gray-300 p-2 outline-none" spellcheck="false" placeholder="Summary" id="text" name="text" maxlength="240" required="">
			<div class="count ml-auto text-gray-400 text-xs font-semibold mb-4"><span id="cur_text">0</span>/240</div>
			<textarea class="description bg-gray-100 sec p-3 h-60 border border-gray-300 outline-none mb-4" spellcheck="false" placeholder="Details" id="details" name="details"></textarea>
			<!-- icons -->
			<div class="icons flex text-gray-500 m-2">
				<svg class="mr-2 cursor-pointer hover:text-gray-700 border rounded-full p-1 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
				<svg class="mr-2 cursor-pointer hover:text-gray-700 border rounded-full p-1 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
				<svg class="mr-2 cursor-pointer hover:text-gray-700 border rounded-full p-1 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" /></svg>
			</div>
			<!-- buttons -->
			<div class="buttons flex">
				<a href="/" class="ml-auto bg-white text-gray-800 font-bold rounded border-b-2 border-red-500 hover:border-red-600 hover:bg-red-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center">
					<span class="mr-2">Cancel</span>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
					<path fill="currentcolor" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z"/>
					</svg>
				</a>
				<button class=" mx-2 bg-white text-gray-800 font-bold rounded border-b-2 border-blue-500 hover:border-blue-600 hover:bg-blue-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit">
					<span class="mr-2">Create Post</span>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
						<path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
					</svg>
				</button>
			</div>
		</div>
	</form>
{% endblock body %}

feed/templates/feed/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load tz %}

{% block head_title %}{{post.text}} by {{post.author.username}}{% endblock %}

{% block body %}
	<!-- https://tailwindcomponents.com/component/testimonial-card -->
	<div class="max-w-full w-full mx-auto py-4 px-8 bg-white shadow-lg rounded-lg my-20">
		<div class="flex justify-center md:justify-end -mt-16">
			{% if post.author.profile.image != "1" %}
				{% thumbnail post.author.profile.image "100x100" crop="center" as im %}
					<img class="w-20 h-20 object-cover rounded-full border-2 border-blue-500" src="{{ im.url }}" alt="avatar">
				{% endthumbnail %}
			{% else %}
				<img src="https://www.publicdomainpictures.net/pictures/40000/velka/question-mark.jpg" alt="" class="w-20 h-20 object-cover rounded-full border-2 border-blue-500">
			{% endif %}
		</div>
		<div>
			<h3 class="my-2 text-gray-800 text-3l font-semibold">{{post.text}}</h3>
			<p class="mt-2 text-gray-600">{{post.details}}</p>
		</div>
		<div class="flex justify-end mt-4">
			<a href="#" class="text-xl font-medium text-indigo-500">
				{% if post.author.first_name or post.author.last_name %}
					{{post.author.first_name}} {{post.author.last_name}}
				{% else %}
					{{post.author.username}}
				{% endif %}
			</a>
		</div>
	</div>

{% endblock %}

feed/templates/feed/homepage.html
{% extends "base.html" %}

{% block head_title %}Today I...{% endblock %}

{% block body %}
	<div id="post-container">
		{% for post in posts %}
			{% include "includes/post.html" with post=post %}
		{% endfor %}
	</div>
{% endblock %}

profiles/templates/profiles/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block head_title %}{{user.username}}{% endblock head_title %}

{% block body %}
	<!-- https://tailwindcomponents.com/component/github-profile-card -->
<div class="w-75 mx-auto">
	<div class="card min-w-sm border border-gray-700 bg-gray-900 text-gray-50 rounded transition-shadow shadow-xl hover:shadow-xl min-w-max">
		{# TODO: add user background image #}
		<div class="w-full card__media"><img src="https://image.freepik.com/free-vector/abstract-binary-code-techno-background_1048-12836.jpg" class="h-48 w-96"></div>
		<div class="flex items-center p-4">
			<div class="relative flex flex-col items-center w-full">
				<div class="h-24 w-24 md rounded-full relative avatar flex items-end justify-end text-purple-400 min-w-max absolute -top-16 flex bg-purple-200 text-purple-100 row-start-1 row-end-3 text-purple-650 ring-2 ring-blue-500">
					{% if user.profile.image != "1" %}
						{% thumbnail user.profile.image "100x100" crop="center" as im %}
							<img class="h-24 w-24 md rounded-full relative" src="{{ im.url }}" alt="avatar">
						{% endthumbnail %}
					{% else %}
						<img src="https://www.publicdomainpictures.net/pictures/40000/velka/question-mark.jpg" alt="" class="h-24 w-24 md rounded-full relative">
					{% endif %}
				</div>
				<div class="flex flex-col space-y-1 justify-center items-center -mt-12 w-full">
					<span class="text-md whitespace-nowrap text-gray-50 font-semibold">{{user.first_name}} {{user.last_name}}</span><span class="text-md whitespace-nowrap text-gray-100">{{user.username}}</span>
					<p class="text-sm text-gray-200">
						{# TODO: show followers #}
						{{user.motto}}
					</p>
					{% if request.user.is_authenticated %}
						{% if request.user.username != user.username %}
							<div class="py-2 flex space-x-2">
								<button data-username="{{user.username}}" data-action="{% if you_follow %}un{% endif %}follow" data-url="{% url 'profiles:follow' user.username %}" type="button" class="follow-button flex justify-center max-h-max whitespace-nowrap focus:outline-none focus:ring focus:border-blue-300 rounded max-w-max border bg-transparent border-blue-500 text-blue-500 hover:bg-blue-500 hover:text-white px-4 py-1 flex items-center hover:shadow-lg">
									<span class="text-sm mx-2 follow-text">{% if you_follow %}Unfollow{% else %}Follow{% endif %}</span>
								</button>
							</div>
						{% else %}
							<div class="py-2 flex space-x-2">
								<button class="flex justify-center max-h-max whitespace-nowrap focus:outline-none focus:ring focus:border-blue-300 rounded max-w-max border bg-transparent border-blue-500 text-blue-500 hover:bg-blue-500 hover:text-white px-4 py-1 flex items-center hover:shadow-lg">
									<span class="text-sm mx-2">Edit</span>
								</button>
							</div>
						{% endif %}
					{% endif %}
					<div
						class="py-4 flex justify-center items-center w-full divide-x divide-gray-400 divide-solid">
						<span class="text-center px-4"><span class="font-bold text-gray-50">{{followers}}</span><br/><span class="text-gray-100"> followers</span></span>
						<span class="text-center px-4"><span class="font-bold text-gray-50">{{followed_by}}</span><br/><span class="text-gray-100"> following</span></span>
						<span class="text-center px-4"><span class="font-bold text-gray-50">{{total_posts}}</span><br/><span class="text-gray-100"> posts</span></span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}